# # 🚀 Backend Developer Integration Guide (MongoDB, React, API)
# 1. Current Implementation (JSON File)
# Pros: Simple, no external dependencies, easy to move between environments.

# Cons: Not suitable for large-scale, high-concurrency production; file locking issues; no indexing; slow for large datasets.

# 2. How to Migrate to MongoDB (Step-by-Step)
# Step 1: Install pymongo
# bash
# pip install pymongo
# Step 2: Update __init__ to accept MongoDB client
# python
# from pymongo import MongoClient, ASCENDING

# class MealRepository:
#     def __init__(self, mongo_uri="mongodb://localhost:27017/", db_name="food_app"):
#         self.client = MongoClient(mongo_uri)
#         self.db = self.client[db_name]
#         self.collection = self.db["meal_plans"]
#         # Create indexes for efficient queries
#         self.collection.create_index("meal_plan_id", unique=True)
#         self.collection.create_index("user_id")
#         self.collection.create_index([("rating", -1)])  # For top-rated queries
#         self.collection.create_index("favorite")
# Step 3: Replace file-based methods with MongoDB CRUD
# _load_meal_plans → Remove, use list(self.collection.find({})) directly.

# _save_meal_plans → Remove, use individual updates.

# save_meal_plan:

# python
# def save_meal_plan(self, user_id, meal_plan):
#     meal_plan_id = str(uuid.uuid4())
#     timestamp = datetime.utcnow().isoformat()
#     record = {
#         "meal_plan_id": meal_plan_id,
#         "user_id": user_id,
#         "created_at": timestamp,
#         "updated_at": timestamp,
#         "favorite": False,
#         "regeneration_count": 0,
#         "rating": None,
#         "meal_plan": meal_plan
#     }
#     self.collection.insert_one(record)
#     return meal_plan_id
# get_meal_plan:

# python
# def get_meal_plan(self, meal_plan_id):
#     return self.collection.find_one({"meal_plan_id": meal_plan_id})
# get_user_meal_plans:

# python
# def get_user_meal_plans(self, user_id):
#     return list(self.collection.find({"user_id": user_id}))
# mark_as_favorite:

# python
# def mark_as_favorite(self, meal_plan_id):
#     result = self.collection.update_one(
#         {"meal_plan_id": meal_plan_id},
#         {"$set": {"favorite": True, "updated_at": datetime.utcnow().isoformat()}}
#     )
#     return result.modified_count > 0
# 3. React Frontend Integration
# React never calls MealRepository directly. It calls the API endpoints in app/api/meal_plans.py.

# Example React call:

# javascript
# // Fetch all meal plans for a user
# const getUserMealPlans = async (userId) => {
#   const response = await fetch(`http://localhost:8000/meal-plans/user/${userId}`);
#   const data = await response.json();
#   return data.meal_plans;
# };

# // Mark a meal plan as favorite
# const markFavorite = async (mealPlanId) => {
#   const response = await fetch(`http://localhost:8000/meal-plans/${mealPlanId}/favorite`, {
#     method: 'POST',
#   });
#   return response.ok;
# };
# 4. Important Notes for Production
# Current (JSON)	MongoDB Migration
# ✅ No external dependencies	✅ Scalable, concurrent writes
# ❌ File I/O not thread-safe	✅ Atomic operations via update_one
# ❌ No indexing	✅ Indexes on user_id, meal_plan_id, rating
# ❌ Manual file rewriting	✅ Document-level updates
# ❌ Limited to local filesystem	✅ Distributed databases (Atlas, replica sets)
# 5. Indexing Recommendations for MongoDB
# Once migrated, create these indexes for optimal performance:

# python
# self.collection.create_index("meal_plan_id", unique=True)  # For fast lookups
# self.collection.create_index("user_id")                     # For user-specific queries
# self.collection.create_index([("rating", -1)])             # For top-rated sorting
# self.collection.create_index([("user_id", 1), ("favorite", 1)])  # For favorite filter
# 
# ============================================================================
# FILE: app/repositories/meal_repository.py
# ROLE: This file is the DATA ACCESS LAYER for meal plans. It provides CRUD
#       operations for meal plans generated by users, including saving, retrieving,
#       updating, favoriting, rating, and managing regeneration counts.
#       Currently uses a JSON file (database/meal_plans.json) for storage, but
#       can be easily migrated to MongoDB by replacing file I/O with database
#       operations.
# CONNECTIONS:
#   - API Layer (app/api/meal_plans.py): The API endpoints for generating
#     meal plans call methods like save_meal_plan, get_user_meal_plans,
#     mark_as_favorite, rate_meal_plan, etc.
#   - MongoDB (Future): To migrate to MongoDB, replace _load_meal_plans,
#     _save_meal_plans, and file-based methods with MongoDB collection CRUD.
#   - React Frontend: React never calls this repository directly. React calls
#     the API endpoints (e.g., POST /meal-plans/generate, GET /meal-plans/user/{user_id})
#     which internally use this repository to store and retrieve meal plans.
# ============================================================================

import json
import uuid

from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional


class MealRepository:
    """
    PURPOSE: Handles all persistence operations for meal plans.
    CURRENT STORAGE: JSON file (simple, portable, no external dependencies).
    KEY FEATURES:
        - Save a new meal plan for a user.
        - Retrieve a single meal plan by ID.
        - Retrieve all meal plans for a user.
        - Delete a meal plan.
        - Mark/unmark a meal plan as favorite.
        - Increment regeneration count (track how many times a plan was re-generated).
        - Rate a meal plan (1-5).
        - Get top-rated meal plans.
    BACKEND NOTE: For production, replace JSON file with MongoDB. The method
                  signatures are designed to be compatible with a MongoDB
                  implementation, so the API layer won't require changes.
    """

    def __init__(
        self,
        storage_file: str = "database/meal_plans.json"
    ):
        """
        PURPOSE: Initialize the repository with the path to the JSON storage file.
        PARAMETERS:
            storage_file (str): Path to the JSON file (default: "database/meal_plans.json").
        BEHAVIOR:
            - Creates the parent directory if it doesn't exist.
            - Calls _initialize_storage() to ensure the file exists.
        """
        self.storage_file = Path(
            storage_file
        )

        self._initialize_storage()

    def _initialize_storage(
        self
    ) -> None:
        """
        PURPOSE: Ensure the storage file and its parent directory exist.
        BEHAVIOR:
            - Creates the 'database/' directory if missing.
            - Creates an empty JSON list '[]' if the file doesn't exist.
        CONNECTS TO: File system (disk).
        """
        self.storage_file.parent.mkdir(
            parents=True,
            exist_ok=True
        )

        if not self.storage_file.exists():
            # Create an empty JSON array as the initial data.
            with open(
                self.storage_file,
                "w",
                encoding="utf-8"
            ) as file:

                json.dump(
                    [],
                    file,
                    indent=4
                )

    def _load_meal_plans(
        self
    ) -> List[Dict]:
        """
        PURPOSE: Load all meal plan records from the JSON file into memory.
        RETURNS: List[Dict] - A list of meal plan dictionaries.
        ERROR HANDLING:
            - If the file doesn't exist or contains invalid JSON, returns an empty list.
        BACKEND NOTE: If migrating to MongoDB, replace this method with
                      `list(self.collection.find({}))`.
        """
        try:
            with open(
                self.storage_file,
                "r",
                encoding="utf-8"
            ) as file:

                data = json.load(
                    file
                )

                if isinstance(
                    data,
                    list
                ):
                    return data

                return []

        except (
            json.JSONDecodeError,
            FileNotFoundError
        ):
            # If the file is corrupted or missing, start fresh.
            return []

    def _save_meal_plans(
        self,
        meal_plans: List[Dict]
    ) -> None:
        """
        PURPOSE: Write the entire meal plans list back to the JSON file.
        PARAMETERS: meal_plans (List[Dict]) - The updated list of meal plans.
        CONNECTS TO: File system (disk).
        BACKEND NOTE: If migrating to MongoDB, this method becomes unnecessary
                      as each operation will directly update the database.
        """
        with open(
            self.storage_file,
            "w",
            encoding="utf-8"
        ) as file:

            json.dump(
                meal_plans,
                file,
                indent=4,
                ensure_ascii=False  # Allows non-ASCII characters (e.g., emojis)
            )

    def save_meal_plan(
        self,
        user_id: str,
        meal_plan: Dict
    ) -> str:
        """
        PURPOSE: Save a new meal plan for a user.
        PARAMETERS:
            user_id (str): The ID of the user who requested the meal plan.
            meal_plan (Dict): The actual meal plan data (structure depends on
                               the MealGenerator output).
        RETURNS: str - A unique UUID for the meal plan entry.
        BEHAVIOR:
            - Generates a UUID4 for meal_plan_id.
            - Adds timestamps (created_at, updated_at).
            - Sets default fields: favorite=False, regeneration_count=0, rating=None.
            - Saves the record to the JSON file.
        CONNECTS TO: API endpoint POST /meal-plans/generate (in app/api/meal_plans.py).
        """
        meal_plans = (
            self._load_meal_plans()
        )

        meal_plan_id = str(
            uuid.uuid4()
        )

        timestamp = (
            datetime.utcnow()
            .isoformat()
        )

        record = {
            "meal_plan_id": meal_plan_id,
            "user_id": user_id,
            "created_at": timestamp,
            "updated_at": timestamp,
            "favorite": False,
            "regeneration_count": 0,
            "rating": None,
            "meal_plan": meal_plan
        }

        meal_plans.append(
            record
        )

        self._save_meal_plans(
            meal_plans
        )

        return meal_plan_id

    def get_meal_plan(
        self,
        meal_plan_id: str
    ) -> Optional[Dict]:
        """
        PURPOSE: Retrieve a single meal plan by its unique ID.
        PARAMETERS:
            meal_plan_id (str): The UUID of the meal plan.
        RETURNS: Optional[Dict] - The meal plan record if found, else None.
        CONNECTS TO: API endpoint GET /meal-plans/{meal_plan_id}.
        """
        for plan in (
            self._load_meal_plans()
        ):
            if (
                plan.get(
                    "meal_plan_id"
                )
                ==
                meal_plan_id
            ):
                return plan

        return None

    def get_user_meal_plans(
        self,
        user_id: str
    ) -> List[Dict]:
        """
        PURPOSE: Retrieve all meal plans for a specific user.
        PARAMETERS:
            user_id (str): The user's ID.
        RETURNS: List[Dict] - All meal plans belonging to that user.
        CONNECTS TO: API endpoint GET /meal-plans/user/{user_id}.
        """
        return [
            plan
            for plan in (
                self._load_meal_plans()
            )
            if (
                plan.get(
                    "user_id"
                )
                ==
                user_id
            )
        ]

    def get_all_meal_plans(
        self
    ) -> List[Dict]:
        """
        PURPOSE: Retrieve all meal plans across all users.
        RETURNS: List[Dict] - All meal plan records.
        CONNECTS TO: API endpoint that might need global statistics
                     (e.g., analytics, admin dashboard).
        """
        return (
            self._load_meal_plans()
        )

    def meal_plan_exists(
        self,
        meal_plan_id: str
    ) -> bool:
        """
        PURPOSE: Check if a meal plan exists by ID.
        PARAMETERS:
            meal_plan_id (str): The UUID of the meal plan.
        RETURNS: bool - True if the meal plan exists, False otherwise.
        CONNECTS TO: API validation before delete/update operations.
        """
        return (
            self.get_meal_plan(
                meal_plan_id
            )
            is not None
        )

    def delete_meal_plan(
        self,
        meal_plan_id: str
    ) -> bool:
        """
        PURPOSE: Delete a meal plan by its ID.
        PARAMETERS:
            meal_plan_id (str): The UUID of the meal plan to delete.
        RETURNS: bool - True if deleted, False if not found.
        CONNECTS TO: API endpoint DELETE /meal-plans/{meal_plan_id}.
        BEHAVIOR: Removes the entry from the list and rewrites the JSON file.
        """
        meal_plans = (
            self._load_meal_plans()
        )

        original_count = len(
            meal_plans
        )

        # Filter out the meal plan with the matching ID.
        meal_plans = [
            plan
            for plan in meal_plans
            if (
                plan.get(
                    "meal_plan_id"
                )
                != meal_plan_id
            )
        ]

        # If the count didn't change, nothing was deleted.
        if (
            len(meal_plans)
            ==
            original_count
        ):
            return False

        self._save_meal_plans(
            meal_plans
        )

        return True

    def mark_as_favorite(
        self,
        meal_plan_id: str
    ) -> bool:
        """
        PURPOSE: Mark a meal plan as favorite (favorite=True).
        PARAMETERS:
            meal_plan_id (str): The UUID of the meal plan.
        RETURNS: bool - True if updated, False if not found.
        CONNECTS TO: API endpoint POST /meal-plans/{meal_plan_id}/favorite.
        BEHAVIOR:
            - Finds the meal plan by ID.
            - Sets favorite=True.
            - Updates updated_at timestamp.
            - Saves changes to file.
        """
        meal_plans = (
            self._load_meal_plans()
        )

        for plan in meal_plans:
            if (
                plan.get(
                    "meal_plan_id"
                )
                ==
                meal_plan_id
            ):
                plan[
                    "favorite"
                ] = True

                plan[
                    "updated_at"
                ] = (
                    datetime.utcnow()
                    .isoformat()
                )

                self._save_meal_plans(
                    meal_plans
                )

                return True

        return False

    def remove_favorite(
        self,
        meal_plan_id: str
    ) -> bool:
        """
        PURPOSE: Remove favorite status from a meal plan (favorite=False).
        PARAMETERS:
            meal_plan_id (str): The UUID of the meal plan.
        RETURNS: bool - True if updated, False if not found.
        CONNECTS TO: API endpoint DELETE /meal-plans/{meal_plan_id}/favorite.
        """
        meal_plans = (
            self._load_meal_plans()
        )

        for plan in meal_plans:
            if (
                plan.get(
                    "meal_plan_id"
                )
                ==
                meal_plan_id
            ):
                plan[
                    "favorite"
                ] = False

                plan[
                    "updated_at"
                ] = (
                    datetime.utcnow()
                    .isoformat()
                )

                self._save_meal_plans(
                    meal_plans
                )

                return True

        return False

    def get_favorite_meal_plans(
        self,
        user_id: str
    ) -> List[Dict]:
        """
        PURPOSE: Retrieve all favorite meal plans for a specific user.
        PARAMETERS:
            user_id (str): The user's ID.
        RETURNS: List[Dict] - All meal plans where favorite=True for that user.
        CONNECTS TO: API endpoint GET /meal-plans/user/{user_id}/favorites.
        """
        return [
            plan
            for plan in (
                self._load_meal_plans()
            )
            if (
                plan.get(
                    "user_id"
                )
                ==
                user_id
                and
                plan.get(
                    "favorite",
                    False
                )
            )
        ]

    def increment_regeneration_count(
        self,
        meal_plan_id: str
    ) -> bool:
        """
        PURPOSE: Increment the regeneration count of a meal plan by 1.
        PARAMETERS:
            meal_plan_id (str): The UUID of the meal plan.
        RETURNS: bool - True if updated, False if not found.
        CONNECTS TO: API endpoint (e.g., POST /meal-plans/{meal_plan_id}/regenerate)
                     that regenerates a meal plan.
        BEHAVIOR: This tracks how many times a user has regenerated (re-generated)
                  the same meal plan. Useful for analytics or limiting regenerations.
        """
        meal_plans = (
            self._load_meal_plans()
        )

        for plan in meal_plans:
            if (
                plan.get(
                    "meal_plan_id"
                )
                ==
                meal_plan_id
            ):
                plan[
                    "regeneration_count"
                ] = (
                    plan.get(
                        "regeneration_count",
                        0
                    )
                    + 1
                )

                plan[
                    "updated_at"
                ] = (
                    datetime.utcnow()
                    .isoformat()
                )

                self._save_meal_plans(
                    meal_plans
                )

                return True

        return False

    def rate_meal_plan(
        self,
        meal_plan_id: str,
        rating: int
    ) -> bool:
        """
        PURPOSE: Assign a rating (1-5) to a meal plan.
        PARAMETERS:
            meal_plan_id (str): The UUID of the meal plan.
            rating (int): The rating value (should be between 1 and 5).
        RETURNS: bool - True if updated, False if not found.
        CONNECTS TO: API endpoint POST /meal-plans/{meal_plan_id}/rate.
        BEHAVIOR: Updates the rating field and the updated_at timestamp.
        BACKEND NOTE: The rating is stored as an integer. The API layer should
                      validate the range (1-5) before calling this method.
        """
        meal_plans = (
            self._load_meal_plans()
        )

        for plan in meal_plans:
            if (
                plan.get(
                    "meal_plan_id"
                )
                ==
                meal_plan_id
            ):
                plan[
                    "rating"
                ] = rating

                plan[
                    "updated_at"
                ] = (
                    datetime.utcnow()
                    .isoformat()
                )

                self._save_meal_plans(
                    meal_plans
                )

                return True

        return False

    def get_top_rated_meal_plans(
        self,
        limit: int = 20
    ) -> List[Dict]:
        """
        PURPOSE: Retrieve the highest-rated meal plans across all users.
        PARAMETERS:
            limit (int): Maximum number of meal plans to return (default 20).
        RETURNS: List[Dict] - A list of meal plans with ratings, sorted by
                 rating descending (highest first).
        CONNECTS TO: API endpoint GET /meal-plans/top-rated (or similar).
        BEHAVIOR:
            - Filters out meal plans with null rating.
            - Sorts by rating in descending order.
            - Returns at most 'limit' entries.
        """
        plans = [
            plan
            for plan in (
                self._load_meal_plans()
            )
            if (
                plan.get(
                    "rating"
                )
                is not None
            )
        ]

        plans.sort(
            key=lambda x:
            x.get(
                "rating",
                0
            ),
            reverse=True
        )

        return plans[:limit]