# ============================================================================
# FILE: app/schemas/food_schema.py
# ROLE: COMPUTE ENGINE DATA MODELS (Microservices Architecture)
#       These Pydantic schemas define the strict JSON structure that the Python 
#       engine uses to format its output before sending it to the Node.js API Gateway.
#
# CONNECTIONS:
#   - Node.js API Gateway: Python returns arrays of these objects to Node.js. 
#   - React Frontend (Indirect): Node.js forwards these exact structures to React.
#   - ML Services: The RankingService and MealGenerator use these schemas to 
#     ensure the AI outputs mathematically sound and consistent data.
# ============================================================================

from typing import Optional
from pydantic import BaseModel, Field

# ==========================================
# FoodSchema – Full Food Data Model
# ==========================================
class FoodSchema(BaseModel):
    """
    PURPOSE: Represents a complete food item with all available fields.
    ROLE: Used by the Python engine when a deep data analysis is required internally.
    ARCHITECTURAL NOTE: Node.js handles standard GET /foods requests natively now. 
                        Python only uses this if it needs to process the full feature set.
    """
    # --- Identifiers & Names ---
    food_id: str                      
    canonical_food_name: str          
    local_name: Optional[str] = None  
    english_name: Optional[str] = None 
    food_variant: Optional[str] = None 

    # --- Geographic & Categorization ---
    state: str                        
    region: str                       
    cuisine_type: Optional[str] = None 
    meal_type: str                    
    meal_role: Optional[str] = None   
    food_category: Optional[str] = None 
    staple_type: Optional[str] = None 
    cooking_method: Optional[str] = None 
    spice_level: Optional[str] = None  
    food_group: Optional[str] = None   
    recommended_with: Optional[str] = None 

    # --- Nutritional Values (Macros & Micros) ---
    calories: float                   
    protein: float                    
    fat: float                        
    carbs: float                      
    fiber_g: float                    
    sodium_mg: float                  
    iron_mg: float                    
    calcium_mg: float                 
    potassium_mg: float               

    # --- Health & Suitability Scores ---
    fullness_score: float             
    practicality_score: float         
    frequency_score: float            
    diabetes_score: float             
    heart_health_score: float         
    muscle_gain_score: float          
    weight_loss_score: float          

    # --- Dietary Flags (0 = No, 1 = Yes) ---
    is_veg: int                       
    contains_egg: int                 
    is_allergen_gluten: int           
    is_allergen_dairy: int            
    is_allergen_nuts: int             
    is_allergen_soy: int              
    is_allergen_shellfish: int        
    is_allergen_eggs: int             
    is_allergen_fish: int             

    # --- Medical Condition Suitability (0 = No, 1 = Yes) ---
    suitable_diabetes: int            
    suitable_hypertension: int        
    suitable_heart_disease: int       
    suitable_thyroid: int             
    suitable_pcos: int                
    suitable_kidney_disease: int      
    suitable_gerd: int                


# ==========================================
# FoodRecommendationSchema – Ranked ML Output
# ==========================================
class FoodRecommendationSchema(BaseModel):
    """
    PURPOSE: Represents a dynamically ranked food item scored by the ML engine.
    ROLE: Python returns an array of these to Node.js when the recommendation 
          algorithm finishes processing the user profile against the food dataset.
    """
    food_id: str
    canonical_food_name: str
    local_name: Optional[str] = None
    english_name: Optional[str] = None
    state: str
    region: str
    meal_type: str

    # Key nutritional information for display
    calories: float
    protein: float
    fat: float
    carbs: float
    fiber_g: float

    # ML Computed Scores
    fullness_score: float
    practicality_score: float
    suitability_score: float        # Overall suitability (composite of all scores).
    ml_score: Optional[float] = None # Score predicted by the ML model (0-100).
    reason: Optional[str] = Field(
        default=None,
        description="Human-readable explanation generated by Python (e.g., 'High protein, low fat')"
    )


# ==========================================
# FoodShortSchema – Minimal Food Info
# ==========================================
class FoodShortSchema(BaseModel):
    """
    PURPOSE: Compact representation to keep API payloads light.
    ROLE: Used heavily by the MealGenerator inside Python to populate the `foods` 
          array inside a daily meal plan without bloating the final JSON size.
    """
    food_id: str
    canonical_food_name: str
    local_name: Optional[str] = None
    english_name: Optional[str] = None
    calories: float
    protein: float
    carbs: float
    fat: float